# Jekyll config file.

# Site Settings
lang: en
# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Israel

# Site details and customization
title:
tagline:
email: matans844@gmail.com
description: >
  A personal website to display my projects, my ideas, and my thoughts about code.
theme: bulma-clean-theme

baseurl: ""
url: ""

# Social (First three Required)
repo: "https://github.com/Matans844/my-website"
github_user: "Matans844"
github_repo: "my-website"
github_branch: "master"
github:
  repository_name: my-website 
  access_token : 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
  repository_owner: Matans844
  repository_url: https://github.com/Matans844/my-website
  scopes:
    - repo

# Update: Not a problem anymore!!!!!!
# Still a problem:
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# But the following works:
# curl -H "Authorization: token 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" https://api.github.com/user --user "Matans844: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"

permalink: pretty
# favicon: /path/to/favicon.png
# gh_sponsor: chrisrhymes
hide_share_buttons: false
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
paginate: 5
paginate_path: "/blog/page:num"

# Comments
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  # shortname: csrhymes
  shortname:

# Extras
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-font-awesome-sass
  - jekyll-github-metadata

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

font-awesome:
  assets: true

#google_analytics: UA-code-here

defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Matan Sheskin"
      layout: post
      image:
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: social-media

collections:
  docs:
    output: true
  